<?php

namespace AppBundle\Repository;

/**
 * PlopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlopRepository extends \Doctrine\ORM\EntityRepository
{
}
